config/routes.rb
Rails.application.routes.draw do
  resources :jungle_book_wolves

end

app/models/jungle_book_wolf.rb
class JungleBookWolf < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jungle_book_wolves_controller.rb
class JungleBookWolvesController < ApplicationController
  before_action :set_jungle_book_wolf, only: [:show, :edit, :update, :destroy]

  # GET /jungle_book_wolves
  # GET /jungle_book_wolves.json
  def index
    @jungle_book_wolves = JungleBookWolf.all
  end

  # GET /jungle_book_wolves/1
  # GET /jungle_book_wolves/1.json
  def show
  end

  # GET /jungle_book_wolves/new
  def new
    @jungle_book_wolf = JungleBookWolf.new
  end

  # GET /jungle_book_wolves/1/edit
  def edit
  end

  # POST /jungle_book_wolves
  # POST /jungle_book_wolves.json
  def create
    @jungle_book_wolf = JungleBookWolf.new(jungle_book_wolf_params)

    respond_to do |format|
      if @jungle_book_wolf.save
        format.html { redirect_to @jungle_book_wolf, notice: 'Jungle book wolf was successfully created.' }
        format.json { render :show, status: :created, location: @jungle_book_wolf }
      else
        format.html { render :new }
        format.json { render json: @jungle_book_wolf.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jungle_book_wolves/1
  # PATCH/PUT /jungle_book_wolves/1.json
  def update
    respond_to do |format|
      if @jungle_book_wolf.update(jungle_book_wolf_params)
        format.html { redirect_to @jungle_book_wolf, notice: 'Jungle book wolf was successfully updated.' }
        format.json { render :show, status: :ok, location: @jungle_book_wolf }
      else
        format.html { render :edit }
        format.json { render json: @jungle_book_wolf.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jungle_book_wolves/1
  # DELETE /jungle_book_wolves/1.json
  def destroy
    @jungle_book_wolf.destroy
    respond_to do |format|
      format.html { redirect_to jungle_book_wolves_url, notice: 'Jungle book wolf was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_jungle_book_wolf
      @jungle_book_wolf = JungleBookWolf.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def jungle_book_wolf_params
      params.require(:jungle_book_wolf).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jungle_book_wolves_helper.rb
module JungleBookWolvesHelper
end

app/views/jungle_book_wolves/_form.html.erb
<%= form_for(@jungle_book_wolf) do |f| %>
  <% if @jungle_book_wolf.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@jungle_book_wolf.errors.count, "error") %> prohibited this jungle_book_wolf from being saved:</h2>

      <ul>
      <% @jungle_book_wolf.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jungle_book_wolves/edit.html.erb
<h1>Editing Jungle Book Wolf</h1>

<%= render 'form' %>

<%= link_to 'Show', @jungle_book_wolf %> |
<%= link_to 'Back', jungle_book_wolves_path %>

app/views/jungle_book_wolves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Jungle Book Wolves</h1>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Description</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @jungle_book_wolves.each do |jungle_book_wolf| %>
        <tr>
          <td><%= jungle_book_wolf.description %></td>
          <td><%= link_to 'Show', jungle_book_wolf %></td>
          <td><%= link_to 'Edit', edit_jungle_book_wolf_path(jungle_book_wolf) %></td>
          <td><%= link_to 'Destroy', jungle_book_wolf, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>

<%= link_to 'New Jungle book wolf', new_jungle_book_wolf_path %>

app/views/jungle_book_wolves/new.html.erb
<h1>New Jungle Book Wolf</h1>

<%= render 'form' %>

<%= link_to 'Back', jungle_book_wolves_path %>

app/views/jungle_book_wolves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @jungle_book_wolf.description %>
</p>

<%= link_to 'Edit', edit_jungle_book_wolf_path(@jungle_book_wolf) %> |
<%= link_to 'Back', jungle_book_wolves_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>JungleBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>